AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
Resources:

  ConfidentialObjectsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-ConfidentialObjects'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !GetAtt ConfidentialDataCdcKinesis.Outputs.KinesisStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

  
  ## KINESIS SOURCE STREAM FOR TIMELINE Change Data Capture
  ConfidentialDataCdcKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-confidential-cdc-stream'
        StreamRetentionPeriodHours: 24

Outputs:
  ConfidentialObjectsDynamoTableName:
    Description: Name of dynamodb table containing fake confidentials informations
    Value: !Ref ConfidentialObjectsDynamoTable

  ConfidentialObjectsDynamoTableArn:
    Description: ARN of dynamodb table containing fake confidentials informations
    Value: !Sub '${ConfidentialObjectsDynamoTable.Arn}'
  

  # Confidential Data Change Data Capture kinesis stream
  ConfidentialDataCdcKinesisStreamName:
    Value: !GetAtt ConfidentialDataCdcKinesis.Outputs.KinesisStreamName
    Description: kinesis stream name for ConfidentialObject dynamo table
  ConfidentialDataCdcKinesisStreamArn:
    Value: !GetAtt ConfidentialDataCdcKinesis.Outputs.KinesisStreamArn
    Description: kinesis stream Arn for ConfidentialObject dynamo table
  ConfidentialDataCdcKinesisKeyArn:
    Value: !GetAtt ConfidentialDataCdcKinesis.Outputs.KinesisStreamKeyArn
    Description: KMS key arn for ConfidentialObject stream decryption
  ConfidentialDataCdcKinesisStreamReadOnlyRoleArn:
    Value: !GetAtt ConfidentialDataCdcKinesis.Outputs.KinesisStreamReadOnlyRoleArn
    Description: KMS key arn for ConfidentialObject stream decryption
