AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  BucketSuffix:
    Type: String
    Default: "001"
    Description: Suffix to the log bucket name

  DataLakeAccountId1:
    Type: String
    Default: '-'
    Description: Data lake can read logs

  DataLakeAccountId2:
    Type: String
    Default: '-'
    Description: Data lake can read logs

  CdcStreamRetentionHours:
    Type: Number
    Default: 24
    Description: 'Change Data Capture Kinesis Data Stream retention period in hours'

  LogsStreamRetentionHours:
    Type: Number
    Default: 24
    Description: 'Cloudwatch Logs Kinesis Data Stream retention period in hours'
    
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

Resources:

  ConfidentialObjectsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-ConfidentialObjects'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

  ###                       LOGS STREAMS PREPARATION                      ###
  ###########################################################################
  # Logs bucket
  LogsBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        BucketSuffix: !Ref BucketSuffix
        DataLakeAccountId1: !Ref DataLakeAccountId1
        DataLakeAccountId2: !Ref DataLakeAccountId2

  # Exporter role
  LogsExporterRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-bucket-access-role.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        LogsBucketName: !GetAtt LogsBucket.Outputs.LogsBucketName
        LogsAccountId: !Ref AWS::AccountId
  
  ## KINESIS SOURCE STREAM FOR Change Data Capture
  ConfidentialInfoCdcKinesisSourceStream:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-confidential-cdc-stream'
        StreamRetentionPeriodHours: !Ref CdcStreamRetentionHours

  ## KINESIS SOURCE STREAM FOR Logs
  ConfidentialInfoLogsKinesisSourceStream:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-confidential-logs-stream'
        StreamRetentionPeriodHours: !Ref LogsStreamRetentionHours

  ###             Export dynamo CDC to Log saving bucket             ###
  ###########################################################################
  CdcToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamArn
        SourceKinesisDataStreamKeyArn: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamKeyArn
        LogsBucketName: !GetAtt LogsBucket.Outputs.LogsBucketName
        LogsExporterRoleArn: !GetAtt LogsExporterRole.Outputs.LogsIngestionRoleArn
        StreamNamePrefix: 'cdcTos3'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn

  ###             Export CloudWatch Logs to Log saving bucket             ###
  ###########################################################################
  LogsToExternalBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-source-stream-to-logs-bucket.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        SourceKinesisDataStreamArn: !GetAtt ConfidentialInfoLogsKinesisSourceStream.Outputs.KinesisStreamArn
        SourceKinesisDataStreamKeyArn: !GetAtt ConfidentialInfoLogsKinesisSourceStream.Outputs.KinesisStreamKeyArn
        LogsBucketName: !GetAtt LogsBucket.Outputs.LogsBucketName
        LogsExporterRoleArn: !GetAtt LogsExporterRole.Outputs.LogsIngestionRoleArn
        StreamNamePrefix: 'logsTos3'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        
Outputs:
  ConfidentialObjectsDynamoTableName:
    Description: Name of dynamodb table containing fake confidentials informations
    Value: !Ref ConfidentialObjectsDynamoTable

  ConfidentialObjectsDynamoTableArn:
    Description: ARN of dynamodb table containing fake confidentials informations
    Value: !Sub '${ConfidentialObjectsDynamoTable.Arn}'
  
  # Log exports outputs
  LogsBucketName:
    Description: The name of the bucket where logs must be exported
    Value: !GetAtt LogsBucket.Outputs.LogsBucketName
  LogsExporterRoleArn:
    Description: Role used to export logs to external bucket
    Value: !GetAtt LogsExporterRole.Outputs.LogsIngestionRoleArn
  LogsExporterPolicyArn:
    Description: Policy used by LogsExporterRoleArn Role
    Value: !GetAtt LogsExporterRole.Outputs.LogsIngestionPolicyArn

  # Confidential Data Change Data Capture kinesis stream
  ConfidentialInfoCdcKinesisSourceStreamName:
    Value: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamName
    Description: kinesis stream name for ConfidentialObject dynamo table
  ConfidentialInfoCdcKinesisSourceStreamArn:
    Value: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamArn
    Description: kinesis stream Arn for ConfidentialObject dynamo table
  ConfidentialInfoCdcKinesisSourceStreamKeyArn:
    Value: !GetAtt ConfidentialInfoCdcKinesisSourceStream.Outputs.KinesisStreamKeyArn
    Description: KMS key arn for ConfidentialObject stream decryption


  # Kinesis Source Stream containing the CloudWatch Logs
  ConfidentialInfoLogsKinesisSourceStreamName:
    Description: 'Kinesis source Logs stream name'
    Value: !GetAtt ConfidentialInfoLogsKinesisSourceStream.Outputs.KinesisStreamName
  ConfidentialInfoLogsKinesisSourceStreamArn:
    Description: 'Kinesis source Logs stream ARN'
    Value: !GetAtt ConfidentialInfoLogsKinesisSourceStream.Outputs.KinesisStreamArn
  ConfidentialInfoLogsKinesisSourceStreamKeyArn:
    Description: 'Kinesis source Logs stream crypto key ARN'
    Value: !GetAtt ConfidentialInfoLogsKinesisSourceStream.Outputs.KinesisStreamKeyArn